### ISSUE TITLE
GifDecoder Library now uses AnimatedGIF

### ISSUE THREAD

**Issue by embedded-creations** [bitbank2/AnimatedGIF#20]
Hi Larry,

After getting a handle on the AnimatedGIF API and the needs of myself and people that use my projects, I decided to turn GifDecoder into mostly a wrapper class that simplifies the interface to AnimatedGIF.  It hides the complicated - at least for a beginner - disposal code inside the class, provides a familiar API for people that used the AnimatedGIFs sketch or GifDecoder in the past, and adds some automatic tracking of stats that AnimatedGIF currently doesn't do unless you parse the whole GIF separate from displaying it.  I made sure to credit you and point people to your library for donations and sponsorships in the README.

https://github.com/pixelmatix/GifDecoder

**Comment by bitbank2** [comment]
Looks good, thank you for doing that. I was thinking to allow a new mode for setups that have enough RAM to hold the decoded image. This optional setup would do all of the ugly pixel operations and just give you the finished frame pointer. For LED matrices, it would be ideal since the maximum image size easily fits in RAM.
