### ISSUE TITLE
Huge ram usage

### ISSUE THREAD

**Issue by tsctrl** [bitbank2/AnimatedGIF#42]
Hi Larry, 

thanks for this great library and sorry for spamming your repo.
after i enabled the AnimatedGif it consume around 23,988 bytes of RAM which quite huge. 

i only require to render 192x64 gif image. is there option/params/config in the library that i can tweak or change to minimize the RAM usage as per my use / needed? do this based on the screen width and height calculation?

edit: i have read this: [reduce memory usage on ESP32](https://github.com/bitbank2/AnimatedGIF/issues/8)

```
AnimatedGIF *pGIF = static_cast<AnimatedGIF *>(my_memory_pool);
```

i not sure if i can use this approach as other stuff/library (wifi, tls, etc2..) memory are controlled by the controller.
can i malloc those memory pool and free later? can shed light on how to use malloc? i just started with c.

this issue is happen after importing the AnimatedGIF.h and no begin was call yet. by only importing the library and not running the gif read, it already consume 23Kb of ram. i have tried the malloc and free as example but seem the RAM usage is still the same.

thanks,
ts

**Comment by bitbank2** [comment]
Hi ts,
I designed the library to not use malloc/free so that you could manage the memory. The AnimatedGIF class/structure has 23k of buffers to do the necessary work. Running the code won't consume any additional memory. You can instantiate the class statically or dynamically or place it in TCM/PSRAM/DDR as you please. You can potentially shrink it a little by reducing the size of the buffers in the class, but you will probably break it in the process. GIF decoding takes lots of memory to hold the dictionary, current line, palette(s), and file buffer.

**Comment by tsctrl** [comment]
hi @bitbank2 ,

could share the approach how to instantiate the class dynamically? does it mean it still consume 23k of memory after instantiated? not sure the purpose there.

thanks!

**Comment by bitbank2** [comment]
Statically:
AnimatedGIF gif; // uses 23k of RAM

Dynamically:
AnimatedGIF *pGIF;
pGIF = new AnimatedGIF; // uses the same 23K of RAM, but this time from the heap
